In [3]:
import numpy as np

In [12]:
x = np.matrix([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
y = np.matrix([[1,2,43,4],[5,6,7,84],[49,10,11,12],[143,144,415,16]])

In [13]:
x

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

In [14]:
x.shape

(4, 4)

In [15]:
y

matrix([[  1,   2,  43,   4],
        [  5,   6,   7,  84],
        [ 49,  10,  11,  12],
        [143, 144, 415,  16]])

In [36]:
x*y

matrix([[ 730,  620, 1750,  272],
        [1522, 1268, 3654,  736],
        [2314, 1916, 5558, 1200],
        [3106, 2564, 7462, 1664]])

In [21]:
z

matrix([[ 730,  620, 1750,  272],
        [1522, 1268, 3654,  736],
        [2314, 1916, 5558, 1200],
        [3106, 2564, 7462, 1664]])

In [30]:
c = np.matrix([[1,2,3],[4,5,6]])

In [31]:
c

matrix([[1, 2, 3],
        [4, 5, 6]])

In [37]:
d = np.matrix([[1,2,3],[4,5,6]])
e = np.matrix([[1,2],[3,4],[5,6]])

In [38]:
d

matrix([[1, 2, 3],
        [4, 5, 6]])

In [39]:
e

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [41]:
d*e

matrix([[22, 28],
        [49, 64]])

In [42]:
from numpy import linalg as  LA 

In [43]:
z = np.matrix([[1,3,1],[2,2,1],[3,5,3]])

In [44]:
z.shape

(3, 3)

In [46]:
LA.matrix_rank(z)

3

In [1]:
import numpy as np

In [13]:
a = np.array([1,2])


In [14]:
b= np.array([3,1])

In [15]:
np.dot(a,b)

5