# Numpy Important Summary


In [65]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [66]:
#bundling of numpy
a = np.array([[1,2,3],[4,5,6]])


In [67]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
#get a shape of array
a.shape

(2, 3)

In [69]:
# get a type of value in array
a.dtype

dtype('int32')

In [70]:
#check rows 
a.ndim

2

In [71]:
#range in numpy
b = np.arange(100)

In [72]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [73]:
#checking  speed of numpy
%timeit [i**2 for i in b]
# 0R
%timeit b**2

18.2 µs ± 179 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
693 ns ± 5.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [74]:
r = range(100)
%timeit [x**2 for x in r]

29.3 µs ± 909 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [75]:
#half a step 
n = np.arange(2,12,3)

In [76]:
n

array([ 2,  5,  8, 11])

In [77]:
#if you want 0 values in matrix
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [78]:
# if you want 1 in matrix
m = np.ones((3,3))

In [79]:
m

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [80]:
#if you want identity matrix
a_ = np.eye((3))

In [81]:
a_

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [82]:
#if you want to fill a matrix with a particular value
zz = np.full((3,3),2)

In [83]:
zz

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [84]:
#if you want only integer values
zzz= np.full((3,3),2.2 ,dtype=np.int)

In [85]:
zzz

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [86]:
# if you want values in diaognal
da = np.diag([1,2,3,4,5,6,67,8])

In [87]:
da

array([[ 1,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  3,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  4,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  5,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  6,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 67,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  8]])

In [203]:
#stacking array horizontaly copies of array eg
v = np.array([1,2,3])
#now i want three copies above array
np.tile(v,(3,1))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [204]:
np.tile(v,(3,3))

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3, 1, 2, 3]])

In [90]:
#finding random value in numpy
np.random.random()
# randon value 2 and 50
50*np.random.random()

28.890406149934773

In [91]:
#create a matrix with random values
np.random.random([3,3])

array([[0.96885807, 0.89364501, 0.05443848],
       [0.85479315, 0.10539653, 0.92855178],
       [0.25223995, 0.37877172, 0.76758664]])

# Video 2 content 

In [92]:
#for example you want to distribute a value from 1,20 in to 100 parts you will do the followinga
l = np.linspace(1,20,100)

In [93]:
l

array([ 1.        ,  1.19191919,  1.38383838,  1.57575758,  1.76767677,
        1.95959596,  2.15151515,  2.34343434,  2.53535354,  2.72727273,
        2.91919192,  3.11111111,  3.3030303 ,  3.49494949,  3.68686869,
        3.87878788,  4.07070707,  4.26262626,  4.45454545,  4.64646465,
        4.83838384,  5.03030303,  5.22222222,  5.41414141,  5.60606061,
        5.7979798 ,  5.98989899,  6.18181818,  6.37373737,  6.56565657,
        6.75757576,  6.94949495,  7.14141414,  7.33333333,  7.52525253,
        7.71717172,  7.90909091,  8.1010101 ,  8.29292929,  8.48484848,
        8.67676768,  8.86868687,  9.06060606,  9.25252525,  9.44444444,
        9.63636364,  9.82828283, 10.02020202, 10.21212121, 10.4040404 ,
       10.5959596 , 10.78787879, 10.97979798, 11.17171717, 11.36363636,
       11.55555556, 11.74747475, 11.93939394, 12.13131313, 12.32323232,
       12.51515152, 12.70707071, 12.8989899 , 13.09090909, 13.28282828,
       13.47474747, 13.66666667, 13.85858586, 14.05050505, 14.24

In [94]:
# you want to see the memory size
l.itemsize

8

In [95]:
#shape and reshape in if reshape if you will give wrong it will give error
np.arange(18).shape

(18,)

In [96]:
np.arange(18).reshape(2,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [97]:
# automatically adjust dimention
np.arange(24).reshape(2,3,-1)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [98]:
#mistake that should be avoided alwas pass using a[[2,4,6]] not like a[2,4,6] eg below to acess elements
a = np.array([2,4,6,8,10,12,14,16])

In [99]:
a

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [100]:
#this is the mistake
a[1,3,5]

IndexError: too many indices for array

In [102]:
#this is how its avoided
a[[1,3,5]]

array([ 4,  8, 12])

In [103]:
#getting elemrntts after a particular no
a[2:]

array([ 6,  8, 10, 12, 14, 16])

In [104]:
a[2:5]

array([ 6,  8, 10])

In [105]:
 # hopping over the indexex
a[0::2]    

array([ 2,  6, 10, 14])

In [106]:
# acessing elements in 2d array
v = np.array([[1,2,3],[4,5,6],[7,8,9]])


In [107]:
v[2,2]

9

In [108]:
# putting conditions
v>2

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [114]:
v[(v>2) & (v<5)]

array([3, 4])

In [121]:
# remember the points

a_ = np.array([1,2,3,4,5,5,6,7,8,9])

In [122]:
a_

array([1, 2, 3, 4, 5, 5, 6, 7, 8, 9])

In [123]:
b_ = a_

In [124]:
b_[0] = 112

In [125]:
a_

array([112,   2,   3,   4,   5,   5,   6,   7,   8,   9])

In [126]:
# to look weather they both share same memory or not 
np.shares_memory(a_,b_)

True

In [127]:
# how to handel above by using copy command 
b_ = a_.copy()

In [128]:
b_[6] = 56

In [129]:
b_

array([112,   2,   3,   4,   5,   5,  56,   7,   8,   9])

In [130]:
a_

array([112,   2,   3,   4,   5,   5,   6,   7,   8,   9])

In [131]:
np.shares_memory(a_,b_)

False

In [134]:
# transpose 
k = np.array([[1,2,3],[4,5,6]])
k.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [135]:
b = np.array([[3,6,7],[4,9,0]])

In [137]:
# comparing 
k == b

array([[False, False, False],
       [ True, False, False]])

In [139]:
# vertical stack eg of K,b
z = np.vstack((k ,b))

In [140]:
z

array([[1, 2, 3],
       [4, 5, 6],
       [3, 6, 7],
       [4, 9, 0]])

In [141]:
# horizontal stack
z_ = np.hstack((k,b))


In [142]:
z_

array([[1, 2, 3, 3, 6, 7],
       [4, 5, 6, 4, 9, 0]])

In [144]:
# sin cos tan and exponential
r =np.arange(1,10)
np.sin(r)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [145]:
np.tan(r)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
       -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [146]:
np.exp(r)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [147]:
# adding all the values in matrix
np.sum(r)

45

In [149]:
# median
np.median(r)

5.0

In [152]:
#standard deviation
r.std()

2.581988897471611

In [153]:
q = np.arange(1,10).reshape(3,3)

In [154]:
q

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [155]:
# calculatin determinants
np.linalg.det(q)

det_ex = np.array([[1,2],[3,4]])

np.linalg.det(det_ex)

det_xy = np.arange(1,5).reshape(2,2)

det_xy


np.linalg.det(det_xy)

-9.51619735392994e-16

In [165]:
# calculating inverse
np.linalg.inv(det_xy)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [166]:
#getting eigen values

np.linalg.eig(det_xy)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [167]:
# dot product 
np.dot(det_xy,det_ex)

array([[ 7, 10],
       [15, 22]])

In [171]:
# performing logical operation like or ,and operations
abool = np.array([1,1,0],dtype= bool)
bbool = np.array([1,0,1],dtype = bool)

In [172]:
np.logical_or(abool,bbool)

array([ True,  True,  True])

In [174]:
np.logical_and(abool,bbool)

array([ True, False, False])

In [176]:
# if there is a huge matrix
np.all(abool == abool)

True

In [178]:
# adding matrix axis wise
a = np.array([[1,2],[4,5]])
a.sum()

12

In [179]:
a.sum(axis=0)

array([5, 7])

In [181]:
# max or min or index where max or min value is stored
a.argmin()


0

In [183]:
a.max()

5

In [184]:
a.min()

1

In [186]:
a.argmax()

3

In [196]:
# trick to add dimention to id array
b = np.array([1,33,5,6,67,7,8,87])
c = b[:,np.newaxis].shape

In [197]:
c

(8, 1)

In [199]:
# sorting a numby array
np.sort(b)

array([ 1,  5,  6,  7,  8, 33, 67, 87])